# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               EDA Blogs
tagline:             'Examine Development & Analysis with Blog'
description:         'Custom recovery for Zenfone 5, custom roms,latest firmware and mods,root android, zenfone 5 xda,asus zenfone 5 xda, All other Stuff and news'
url:                 http://edablogs.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Pawneshwer Gupta
  url:               https://twitter.com/pawneshwer
  email:             pawneshwergupta@gmail.com

# Custom vars
version:             1.0.0
permalink: /:categories/:title
